#pragma once

#define EE_HANDS
#define DYNAMIC_KEYMAP_LAYER_COUNT 6

#define SPLIT_LAYER_STATE_ENABLE
#define SPLIT_LED_STATE_ENABLE

#define TAPPING_TERM 220
#define PERMISSIVE_HOLD
#define QUICK_TAP_TERM 0
#define COMBO_TERM 60
